version: 2
jobs:
  build:
    working_directory: ~/tics
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - restore_cache:
          key: tics-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: tics-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"
       # Lint the source code
      - run:
          name: Linting
          command: npm run lint
    # Test the source code
      - run:
         name: Testing
         command: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
        
        